[2025-05-24T21:37:34.259+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-24T21:37:34.276+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: supplier_data_etl_pipeline.extract_api_data manual__2025-05-24T21:27:11.565936+00:00 [queued]>
[2025-05-24T21:37:34.280+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: supplier_data_etl_pipeline.extract_api_data manual__2025-05-24T21:27:11.565936+00:00 [queued]>
[2025-05-24T21:37:34.280+0000] {taskinstance.py:2303} INFO - Starting attempt 3 of 6
[2025-05-24T21:37:34.289+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): extract_api_data> on 2025-05-24 21:27:11.565936+00:00
[2025-05-24T21:37:34.297+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=937) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-24T21:37:34.300+0000] {standard_task_runner.py:63} INFO - Started process 943 to run task
[2025-05-24T21:37:34.300+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'supplier_data_etl_pipeline', 'extract_api_data', 'manual__2025-05-24T21:27:11.565936+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/supplier_dag.py', '--cfg-path', '/tmp/tmp7yx2pchg']
[2025-05-24T21:37:34.301+0000] {standard_task_runner.py:91} INFO - Job 74: Subtask extract_api_data
[2025-05-24T21:37:34.343+0000] {task_command.py:426} INFO - Running <TaskInstance: supplier_data_etl_pipeline.extract_api_data manual__2025-05-24T21:27:11.565936+00:00 [running]> on host a7d211f7b093
[2025-05-24T21:37:34.422+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='supplier_data_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_api_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-24T21:27:11.565936+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-24T21:27:11.565936+00:00'
[2025-05-24T21:37:34.427+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-24T21:37:34.431+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-24T21:37:34.432+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl.py", line 64, in extract_api
    with open("./opt/airflow/dags/api_suppliers.json") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './opt/airflow/dags/api_suppliers.json'
[2025-05-24T21:37:34.495+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=supplier_data_etl_pipeline, task_id=extract_api_data, execution_date=20250524T212711, start_date=20250524T213734, end_date=20250524T213734
[2025-05-24T21:37:34.507+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 74 for task extract_api_data ([Errno 2] No such file or directory: './opt/airflow/dags/api_suppliers.json'; 943)
[2025-05-24T21:37:34.522+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-24T21:37:34.559+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-24T21:37:34.561+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
