[2025-05-24T21:11:01.917+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-24T21:11:01.957+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: supplier_data_etl_pipeline.extract_csv_data manual__2025-05-24T21:10:56.940417+00:00 [queued]>
[2025-05-24T21:11:01.964+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: supplier_data_etl_pipeline.extract_csv_data manual__2025-05-24T21:10:56.940417+00:00 [queued]>
[2025-05-24T21:11:01.965+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2025-05-24T21:11:02.007+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): extract_csv_data> on 2025-05-24 21:10:56.940417+00:00
[2025-05-24T21:11:02.034+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'supplier_data_etl_pipeline', 'extract_csv_data', 'manual__2025-05-24T21:10:56.940417+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/supplier_dag.py', '--cfg-path', '/tmp/tmp0fw45_fi']
[2025-05-24T21:11:02.037+0000] {standard_task_runner.py:91} INFO - Job 20: Subtask extract_csv_data
[2025-05-24T21:11:02.034+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=442) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-24T21:11:02.038+0000] {standard_task_runner.py:63} INFO - Started process 457 to run task
[2025-05-24T21:11:28.333+0000] {task_command.py:426} INFO - Running <TaskInstance: supplier_data_etl_pipeline.extract_csv_data manual__2025-05-24T21:10:56.940417+00:00 [running]> on host a7d211f7b093
[2025-05-24T21:11:28.743+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='supplier_data_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_csv_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-24T21:10:56.940417+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-24T21:10:56.940417+00:00'
[2025-05-24T21:11:28.752+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-24T21:11:28.783+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-24T21:11:28.792+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl.py", line 19, in extract_csv
    df = pd.read_csv("./mock_supplier_data.csv")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './mock_supplier_data.csv'
[2025-05-24T21:11:28.905+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=supplier_data_etl_pipeline, task_id=extract_csv_data, execution_date=20250524T211056, start_date=20250524T211101, end_date=20250524T211128
[2025-05-24T21:11:28.947+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 20 for task extract_csv_data ([Errno 2] No such file or directory: './mock_supplier_data.csv'; 457)
[2025-05-24T21:11:29.001+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-24T21:11:29.093+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-24T21:11:29.098+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
