[2025-05-24T21:40:08.036+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-24T21:40:08.056+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: supplier_data_etl_pipeline.extract_api_data manual__2025-05-24T21:17:11.637733+00:00 [queued]>
[2025-05-24T21:40:08.062+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: supplier_data_etl_pipeline.extract_api_data manual__2025-05-24T21:17:11.637733+00:00 [queued]>
[2025-05-24T21:40:08.063+0000] {taskinstance.py:2303} INFO - Starting attempt 5 of 6
[2025-05-24T21:40:08.087+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): extract_api_data> on 2025-05-24 21:17:11.637733+00:00
[2025-05-24T21:40:08.098+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=986) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-24T21:40:08.103+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'supplier_data_etl_pipeline', 'extract_api_data', 'manual__2025-05-24T21:17:11.637733+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/supplier_dag.py', '--cfg-path', '/tmp/tmp7xxiwcbc']
[2025-05-24T21:40:08.105+0000] {standard_task_runner.py:63} INFO - Started process 997 to run task
[2025-05-24T21:40:08.105+0000] {standard_task_runner.py:91} INFO - Job 81: Subtask extract_api_data
[2025-05-24T21:40:08.184+0000] {task_command.py:426} INFO - Running <TaskInstance: supplier_data_etl_pipeline.extract_api_data manual__2025-05-24T21:17:11.637733+00:00 [running]> on host a7d211f7b093
[2025-05-24T21:40:08.270+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='supplier_data_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_api_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-24T21:17:11.637733+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-24T21:17:11.637733+00:00'
[2025-05-24T21:40:08.273+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-24T21:40:08.274+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-24T21:40:08.274+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl.py", line 64, in extract_api
    with open("./opt/airflow/dags/api_suppliers.json") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './opt/airflow/dags/api_suppliers.json'
[2025-05-24T21:40:08.284+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=supplier_data_etl_pipeline, task_id=extract_api_data, execution_date=20250524T211711, start_date=20250524T214008, end_date=20250524T214008
[2025-05-24T21:40:08.294+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 81 for task extract_api_data ([Errno 2] No such file or directory: './opt/airflow/dags/api_suppliers.json'; 997)
[2025-05-24T21:40:08.329+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-24T21:40:08.389+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-24T21:40:08.394+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
